# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-24 11:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amarreapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Combustible',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('GASL', 'Gasoil'), ('GSLN', 'Gasolina')], default='GASL', max_length=4)),
                ('precio_litro', models.DecimalField(decimal_places=2, max_digits=4)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
