# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-24 12:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amarreapp', '0003_embarcacion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='combustible',
            old_name='creado',
            new_name='timestamp',
        ),
        migrations.RenameField(
            model_name='combustible',
            old_name='modificado',
            new_name='updated',
        ),
        migrations.AlterField(
            model_name='combustible',
            name='precio_litro',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
