# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-24 12:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amarreapp', '0004_auto_20170124_1223'),
    ]

    operations = [
        migrations.AddField(
            model_name='combustible',
            name='nombre',
            field=models.CharField(default=' ', max_length=50),
        ),
        migrations.AddField(
            model_name='embarcacion',
            name='matricula',
            field=models.CharField(default=' ', max_length=40),
        ),
        migrations.AddField(
            model_name='embarcacion',
            name='nombre',
            field=models.CharField(default=' ', max_length=50),
        ),
    ]
