# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-25 08:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('amarreapp', '0005_auto_20170124_1255'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domicilio', models.TextField(blank=True, verbose_name='street')),
                ('localidad', models.CharField(blank=True, max_length=200, verbose_name='city')),
                ('provincia', models.CharField(blank=True, max_length=200, verbose_name='province')),
                ('codigo_postal', models.CharField(blank=True, max_length=10, verbose_name='postal code')),
                ('pais', models.CharField(max_length=100, verbose_name='country')),
                ('correo_electronico', models.EmailField(max_length=254)),
                ('pagina_web', models.URLField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Puerto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default=' ', max_length=50)),
                ('isla', models.CharField(choices=[('MA', 'Mallorca'), ('ME', 'Menorca'), ('IB', 'Ibiza')], default='MA', max_length=2)),
                ('latitud', models.FloatField()),
                ('longitud', models.FloatField()),
                ('rampa', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('contacto', models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='amarreapp.Contacto')),
            ],
        ),
    ]
