# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-26 08:11
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amarreapp', '0008_auto_20170126_0803'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contacto',
            old_name='pagina_web',
            new_name='url',
        ),
        migrations.AlterField(
            model_name='contacto',
            name='correo_electronico',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='fax',
            field=models.CharField(blank=True, max_length=16, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='pais',
            field=models.CharField(blank=True, max_length=100, verbose_name='country'),
        ),
    ]
