# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-26 12:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('amarreapp', '0009_auto_20170126_0811'),
    ]

    operations = [
        migrations.AddField(
            model_name='embarcacion',
            name='propietario',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
