# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-31 13:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('amarreapp', '0010_embarcacion_propietario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prediccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(blank=True, verbose_name='name')),
                ('zona', models.TextField(blank=True, verbose_name='zone')),
                ('origen', models.CharField(choices=[('PE', 'Personal'), ('AE', 'Aemet')], default='PE', max_length=2)),
                ('prediccion', models.TextField(blank=True)),
                ('estado_de_la_mar', models.CharField(choices=[('0', 'Calma'), ('1', 'Rizada'), ('2', 'Marejadilla'), ('3', 'Marejada'), ('4', 'Fuerte Marejada'), ('5', 'Gruesa'), ('6', 'Muy Gruesa'), ('7', 'Arbolada'), ('8', 'Montañosa'), ('9', 'Enorme')], default='0', max_length=1)),
                ('direccion', models.CharField(choices=[('NT', 'Norte'), ('NE', 'Noreste'), ('ES', 'Este'), ('SE', 'Sureste'), ('SU', 'Sur'), ('SO', 'Suroeste'), ('OE', 'Oeste'), ('NO', 'Noroeste')], default='SU', max_length=2)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('autor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
