# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-31 13:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amarreapp', '0011_prediccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prediccion',
            name='nombre',
            field=models.TextField(blank=True, max_length=160, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='prediccion',
            name='zona',
            field=models.CharField(blank=True, max_length=80, verbose_name='zone'),
        ),
    ]
