# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-31 13:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amarreapp', '0012_auto_20170131_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prediccion',
            name='nombre',
            field=models.CharField(blank=True, max_length=80, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='prediccion',
            name='prediccion',
            field=models.TextField(blank=True, max_length=160),
        ),
    ]
