# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-25 22:53
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('amarreapp', '0013_auto_20170131_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='puerto',
            name='duchas',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='embarcacion',
            name='calado',
            field=models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(3.99)]),
        ),
        migrations.AlterField(
            model_name='embarcacion',
            name='eslora',
            field=models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(4.0), django.core.validators.MaxValueValidator(15.99)]),
        ),
        migrations.AlterField(
            model_name='embarcacion',
            name='manga',
            field=models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(5.99)]),
        ),
        migrations.AlterField(
            model_name='embarcacion',
            name='motor_combustible',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='amarreapp.Combustible'),
        ),
        migrations.AlterField(
            model_name='puerto',
            name='isla',
            field=models.CharField(choices=[('MA', 'Mallorca'), ('ME', 'Menorca'), ('IB', 'Ibiza'), ('FO', 'Formentera')], default='MA', max_length=2),
        ),
    ]
