# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-25 22:55
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amarreapp', '0014_auto_20170425_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='embarcacion',
            name='calado',
            field=models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(3.99)]),
        ),
    ]
