# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-27 23:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amarreapp', '0015_auto_20170425_2255'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amarre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default=' ', max_length=50, verbose_name='nombre')),
                ('eslora', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='length')),
                ('manga', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='beam')),
                ('agua', models.BooleanField(default=True, verbose_name='water')),
                ('electricidad', models.BooleanField(default=True, verbose_name='electricity')),
                ('info', models.TextField(blank=True, max_length=160, verbose_name='information')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('puertos', models.ManyToManyField(to='amarreapp.Puerto')),
            ],
        ),
        migrations.AlterField(
            model_name='prediccion',
            name='nombre',
            field=models.CharField(blank=True, max_length=80, verbose_name='nombre'),
        ),
    ]
