# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-28 00:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amarreapp', '0017_auto_20170428_0002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='precio_mes',
            name='abril',
        ),
        migrations.RemoveField(
            model_name='precio_mes',
            name='febrero',
        ),
        migrations.RemoveField(
            model_name='precio_mes',
            name='marzo',
        ),
        migrations.AlterField(
            model_name='precio_mes',
            name='enero',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=4),
        ),
    ]
