# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-28 00:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('amarreapp', '0018_auto_20170428_0004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amarre',
            name='precio_dia',
            field=models.ForeignKey(auto_created=True, on_delete=django.db.models.deletion.CASCADE, to='amarreapp.Precio_mes'),
        ),
    ]
