# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-07 16:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amarreapp', '0019_auto_20170428_0020'),
    ]

    operations = [
        migrations.AddField(
            model_name='precio_mes',
            name='abril',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=4),
        ),
        migrations.AddField(
            model_name='precio_mes',
            name='agosto',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=4),
        ),
        migrations.AddField(
            model_name='precio_mes',
            name='diciembre',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=4),
        ),
        migrations.AddField(
            model_name='precio_mes',
            name='febrero',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=4),
        ),
        migrations.AddField(
            model_name='precio_mes',
            name='julio',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=4),
        ),
        migrations.AddField(
            model_name='precio_mes',
            name='junio',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=4),
        ),
        migrations.AddField(
            model_name='precio_mes',
            name='marzo',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=4),
        ),
        migrations.AddField(
            model_name='precio_mes',
            name='mayo',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=4),
        ),
        migrations.AddField(
            model_name='precio_mes',
            name='noviembre',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=4),
        ),
        migrations.AddField(
            model_name='precio_mes',
            name='octubre',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=4),
        ),
        migrations.AddField(
            model_name='precio_mes',
            name='septiembre',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=4),
        ),
    ]
