# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-07 16:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('amarreapp', '0020_auto_20170507_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amarre',
            name='precio_dia',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='amarreapp.Precio_mes'),
        ),
    ]
