# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-07 16:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('amarreapp', '0021_auto_20170507_1644'),
    ]

    operations = [
        migrations.CreateModel(
            name='Precio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enero', models.DecimalField(decimal_places=2, default=10.0, max_digits=4)),
                ('febrero', models.DecimalField(decimal_places=2, default=10.0, max_digits=4)),
                ('marzo', models.DecimalField(decimal_places=2, default=10.0, max_digits=4)),
                ('abril', models.DecimalField(decimal_places=2, default=10.0, max_digits=4)),
                ('mayo', models.DecimalField(decimal_places=2, default=10.0, max_digits=4)),
                ('junio', models.DecimalField(decimal_places=2, default=10.0, max_digits=4)),
                ('julio', models.DecimalField(decimal_places=2, default=10.0, max_digits=4)),
                ('agosto', models.DecimalField(decimal_places=2, default=10.0, max_digits=4)),
                ('septiembre', models.DecimalField(decimal_places=2, default=10.0, max_digits=4)),
                ('octubre', models.DecimalField(decimal_places=2, default=10.0, max_digits=4)),
                ('noviembre', models.DecimalField(decimal_places=2, default=10.0, max_digits=4)),
                ('diciembre', models.DecimalField(decimal_places=2, default=10.0, max_digits=4)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='amarre',
            name='precio_dia',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='amarreapp.Precio'),
        ),
        migrations.DeleteModel(
            name='Precio_mes',
        ),
    ]
