# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-07 16:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amarreapp', '0022_auto_20170507_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='precio',
            name='nombre',
            field=models.CharField(default=' ', max_length=50, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='precio',
            name='abril',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=4, verbose_name='Abril'),
        ),
        migrations.AlterField(
            model_name='precio',
            name='agosto',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=4, verbose_name='Agosto'),
        ),
        migrations.AlterField(
            model_name='precio',
            name='diciembre',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=4, verbose_name='Diciembre'),
        ),
        migrations.AlterField(
            model_name='precio',
            name='enero',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=4, verbose_name='Enero'),
        ),
        migrations.AlterField(
            model_name='precio',
            name='febrero',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=4, verbose_name='Febrero'),
        ),
        migrations.AlterField(
            model_name='precio',
            name='julio',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=4, verbose_name='Julio'),
        ),
        migrations.AlterField(
            model_name='precio',
            name='junio',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=4, verbose_name='Junio'),
        ),
        migrations.AlterField(
            model_name='precio',
            name='marzo',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=4, verbose_name='Marzo'),
        ),
        migrations.AlterField(
            model_name='precio',
            name='mayo',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=4, verbose_name='Mayo'),
        ),
        migrations.AlterField(
            model_name='precio',
            name='noviembre',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=4, verbose_name='Noviembre'),
        ),
        migrations.AlterField(
            model_name='precio',
            name='octubre',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=4, verbose_name='Octubre'),
        ),
        migrations.AlterField(
            model_name='precio',
            name='septiembre',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=4, verbose_name='Septiembre'),
        ),
        migrations.AlterField(
            model_name='precio',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='TimeStamp'),
        ),
        migrations.AlterField(
            model_name='precio',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated'),
        ),
    ]
