# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-07 17:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amarreapp', '0023_auto_20170507_1654'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amarre',
            name='puertos',
        ),
        migrations.AddField(
            model_name='puerto',
            name='amarre',
            field=models.ManyToManyField(to='amarreapp.Amarre'),
        ),
    ]
