# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-10 00:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amarreapp', '0024_auto_20170507_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='puerto',
            name='informacion',
            field=models.TextField(blank=True, max_length=160, verbose_name='information'),
        ),
        migrations.AlterField(
            model_name='puerto',
            name='isla',
            field=models.CharField(choices=[('MA', 'Mallorca'), ('ME', 'Menorca'), ('IB', 'Ibiza'), ('FO', 'Formentera')], default='MA', max_length=2, verbose_name='island'),
        ),
        migrations.AlterField(
            model_name='puerto',
            name='latitud',
            field=models.FloatField(verbose_name='latitude'),
        ),
        migrations.AlterField(
            model_name='puerto',
            name='longitud',
            field=models.FloatField(verbose_name='longitude'),
        ),
        migrations.AlterField(
            model_name='puerto',
            name='nombre',
            field=models.CharField(default=' ', max_length=50, verbose_name='nombre'),
        ),
    ]
