# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-10 00:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amarreapp', '0025_auto_20170510_0016'),
    ]

    operations = [
        migrations.AddField(
            model_name='puerto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='images', verbose_name='image'),
        ),
    ]
