# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-15 23:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('amarreapp', '0026_puerto_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Distancia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distancia', models.PositiveIntegerField(verbose_name='distance')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('destino', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='destination', to='amarreapp.Puerto')),
                ('origen', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source', to='amarreapp.Puerto')),
            ],
        ),
    ]
