# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-16 20:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('amarreapp', '0028_auto_20170516_0009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prediccion',
            name='autor',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
