# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-16 21:53
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amarreapp', '0029_auto_20170516_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puerto',
            name='latitud',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(38.675), django.core.validators.MaxValueValidator(40.096666666666664)], verbose_name='latitude'),
        ),
        migrations.AlterField(
            model_name='puerto',
            name='longitud',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(38.675), django.core.validators.MaxValueValidator(40.096666666666664)], verbose_name='longitude'),
        ),
    ]
