# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-16 22:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('amarreapp', '0030_auto_20170516_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distancia',
            name='destino',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='destination', to='amarreapp.Puerto'),
        ),
        migrations.AlterField(
            model_name='distancia',
            name='origen',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source', to='amarreapp.Puerto'),
        ),
    ]
