# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-16 22:21
from __future__ import unicode_literals

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amarreapp', '0031_auto_20170516_2205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='distancia',
            name='distancia_km',
        ),
        migrations.AddField(
            model_name='distancia',
            name='distancia_nmi',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='distance_nmi'),
        ),
        migrations.AlterField(
            model_name='puerto',
            name='longitud',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(1.2130555555555556), django.core.validators.MaxValueValidator(4.316666666666666)], verbose_name='longitude'),
        ),
    ]
