# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-19 01:10
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('amarreapp', '0033_embarcacion_velocidad_kn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amarre',
            name='agua',
            field=models.BooleanField(default=True, verbose_name='agua'),
        ),
        migrations.AlterField(
            model_name='amarre',
            name='electricidad',
            field=models.BooleanField(default=True, verbose_name='electricidad'),
        ),
        migrations.AlterField(
            model_name='amarre',
            name='info',
            field=models.TextField(blank=True, max_length=160, verbose_name='información'),
        ),
        migrations.AlterField(
            model_name='amarre',
            name='manga',
            field=models.DecimalField(decimal_places=2, max_digits=4, verbose_name='manga'),
        ),
        migrations.AlterField(
            model_name='amarre',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='amarre',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización'),
        ),
        migrations.AlterField(
            model_name='combustible',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='combustible',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización'),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='codigo_postal',
            field=models.CharField(blank=True, max_length=10, verbose_name='código postal'),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='correo_electronico',
            field=models.EmailField(blank=True, max_length=254, verbose_name='correo electrónico'),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='domicilio',
            field=models.TextField(blank=True, verbose_name='calle'),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='localidad',
            field=models.CharField(blank=True, max_length=200, verbose_name='ciudad'),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='pais',
            field=models.CharField(blank=True, max_length=100, verbose_name='país'),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='provincia',
            field=models.CharField(blank=True, max_length=200, verbose_name='provincia'),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='telefono',
            field=models.CharField(blank=True, max_length=16, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')], verbose_name='teléfono'),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización'),
        ),
        migrations.AlterField(
            model_name='distancia',
            name='destino',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='destino', to='amarreapp.Puerto'),
        ),
        migrations.AlterField(
            model_name='distancia',
            name='origen',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='origen', to='amarreapp.Puerto'),
        ),
        migrations.AlterField(
            model_name='distancia',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='distancia',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización'),
        ),
        migrations.AlterField(
            model_name='embarcacion',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='embarcacion',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización'),
        ),
        migrations.AlterField(
            model_name='embarcacion',
            name='velocidad_kn',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='precio',
            name='diciembre',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=4, verbose_name='Deciembre'),
        ),
        migrations.AlterField(
            model_name='precio',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='precio',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización'),
        ),
        migrations.AlterField(
            model_name='prediccion',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='prediccion',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización'),
        ),
        migrations.AlterField(
            model_name='prediccion',
            name='zona',
            field=models.CharField(blank=True, max_length=80, verbose_name='zona'),
        ),
        migrations.AlterField(
            model_name='puerto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='images', verbose_name='imagen'),
        ),
        migrations.AlterField(
            model_name='puerto',
            name='informacion',
            field=models.TextField(blank=True, max_length=160, verbose_name='información'),
        ),
        migrations.AlterField(
            model_name='puerto',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='puerto',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización'),
        ),
    ]
