# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-21 18:44
from __future__ import unicode_literals

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amarreapp', '0034_auto_20170519_0110'),
    ]

    operations = [
        migrations.AddField(
            model_name='prediccion',
            name='dias',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)]),
        ),
        migrations.AddField(
            model_name='prediccion',
            name='fecha',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='prediccion',
            name='zona',
            field=models.CharField(choices=[('NO_MA', 'Noroeste Mallorca'), ('NE_MA', 'Noreste Mallorca'), ('ES_MA', 'Este Mallorca'), ('SU_MA', 'Sur Mallorca'), ('CN_ME', 'Canal de Menorca'), ('NO_ME', 'Norte Menorca'), ('SU_ME', 'Sur Menorca'), ('CN_IB', 'Canal de Ibiza'), ('IBIZA', 'Ibiza'), ('FORMN', 'Formentera')], default='NO_MA', max_length=5, verbose_name='zona'),
        ),
    ]
