# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-21 18:53
from __future__ import unicode_literals

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amarreapp', '0035_auto_20170521_1844'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prediccion',
            name='direccion',
        ),
        migrations.AlterField(
            model_name='prediccion',
            name='dias',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)], verbose_name='days'),
        ),
        migrations.AlterField(
            model_name='prediccion',
            name='fecha',
            field=models.DateField(default=datetime.datetime.now, verbose_name='fecha'),
        ),
        migrations.AlterField(
            model_name='prediccion',
            name='origen',
            field=models.CharField(choices=[('PE', 'Personal'), ('AE', 'Aemet')], default='PE', max_length=2, verbose_name='origen'),
        ),
        migrations.AlterField(
            model_name='prediccion',
            name='prediccion',
            field=models.TextField(blank=True, max_length=160, verbose_name='forecast'),
        ),
    ]
