# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-21 22:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amarreapp', '0036_auto_20170521_1853'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prediccion',
            name='fecha',
        ),
        migrations.AddField(
            model_name='prediccion',
            name='fecha_fin',
            field=models.DateField(blank=True, default=datetime.datetime.now, verbose_name='end_date'),
        ),
        migrations.AddField(
            model_name='prediccion',
            name='fecha_inicio',
            field=models.DateField(default=datetime.datetime.now, verbose_name='start_date'),
        ),
    ]
