# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-25 21:52
from __future__ import unicode_literals

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amarreapp', '0037_auto_20170521_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prediccion',
            name='dias',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)], verbose_name='dias'),
        ),
        migrations.AlterField(
            model_name='prediccion',
            name='fecha_inicio',
            field=models.DateField(default=datetime.datetime.now, verbose_name='fecha inicio'),
        ),
        migrations.AlterField(
            model_name='puerto',
            name='amarre',
            field=models.ManyToManyField(default=None, null=True, to='amarreapp.Amarre'),
        ),
    ]
