# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-30 00:27
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('amarreapp', '0038_auto_20170525_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='combustible',
            name='precio_litro',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='puerto',
            name='amarre',
            field=models.ManyToManyField(blank=True, default=None, null=True, to='amarreapp.Amarre'),
        ),
        migrations.AlterField(
            model_name='puerto',
            name='contacto',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='amarreapp.Contacto'),
        ),
    ]
