# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-25 21:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amarreapp', '0038_auto_20170525_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puerto',
            name='amarre',
            field=models.ManyToManyField(blank=True, default=None, null=True, to='amarreapp.Amarre'),
        ),
    ]
