# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-27 00:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('amarreapp', '0039_auto_20170525_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puerto',
            name='contacto',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='amarreapp.Contacto'),
        ),
    ]
