# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-30 23:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amarreapp', '0041_auto_20170529_1836'),
        ('amarreapp', '0039_auto_20170530_0027'),
    ]

    operations = [
    ]
