# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-30 23:06
from __future__ import unicode_literals

import datetime
from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amarreapp', '0042_merge_20170530_2306'),
    ]

    operations = [
        migrations.AddField(
            model_name='puerto',
            name='distancias',
            field=models.ManyToManyField(through='amarreapp.Distancia', to='amarreapp.Puerto'),
        ),
        migrations.AlterField(
            model_name='amarre',
            name='eslora',
            field=models.DecimalField(decimal_places=2, max_digits=4, verbose_name='eslora'),
        ),
        migrations.AlterField(
            model_name='distancia',
            name='distancia_nmi',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='distancia_nmi'),
        ),
        migrations.AlterField(
            model_name='prediccion',
            name='fecha_fin',
            field=models.DateField(blank=True, default=datetime.datetime.now, verbose_name='fecha fin'),
        ),
        migrations.AlterField(
            model_name='prediccion',
            name='prediccion',
            field=models.TextField(blank=True, max_length=160, verbose_name='predicción'),
        ),
        migrations.AlterField(
            model_name='puerto',
            name='isla',
            field=models.CharField(choices=[('MA', 'Mallorca'), ('ME', 'Menorca'), ('IB', 'Ibiza'), ('FO', 'Formentera')], default='MA', max_length=2, verbose_name='isla'),
        ),
        migrations.AlterField(
            model_name='puerto',
            name='latitud',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(38.675), django.core.validators.MaxValueValidator(40.096666666666664)], verbose_name='latitud'),
        ),
        migrations.AlterField(
            model_name='puerto',
            name='longitud',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(1.2130555555555556), django.core.validators.MaxValueValidator(4.316666666666666)], verbose_name='longitud'),
        ),
    ]
