# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-30 23:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amarreapp', '0044_auto_20170530_2316'),
    ]

    operations = [
        migrations.AddField(
            model_name='puerto',
            name='testdistancias',
            field=models.ManyToManyField(related_name='_puerto_testdistancias_+', to='amarreapp.Puerto'),
        ),
    ]
