# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-30 23:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amarreapp', '0045_puerto_testdistancias'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='puerto',
            name='testdistancias',
        ),
    ]
