# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-31 19:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amarreapp', '0046_remove_puerto_testdistancias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='embarcacion',
            name='matricula',
            field=models.CharField(blank=True, default=' ', max_length=40),
        ),
        migrations.AlterField(
            model_name='precio',
            name='abril',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=5, verbose_name='Abril'),
        ),
        migrations.AlterField(
            model_name='precio',
            name='agosto',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=5, verbose_name='Agosto'),
        ),
        migrations.AlterField(
            model_name='precio',
            name='diciembre',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=5, verbose_name='Deciembre'),
        ),
        migrations.AlterField(
            model_name='precio',
            name='enero',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=5, verbose_name='Enero'),
        ),
        migrations.AlterField(
            model_name='precio',
            name='febrero',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=5, verbose_name='Febrero'),
        ),
        migrations.AlterField(
            model_name='precio',
            name='julio',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=5, verbose_name='Julio'),
        ),
        migrations.AlterField(
            model_name='precio',
            name='junio',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=5, verbose_name='Junio'),
        ),
        migrations.AlterField(
            model_name='precio',
            name='marzo',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=5, verbose_name='Marzo'),
        ),
        migrations.AlterField(
            model_name='precio',
            name='mayo',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=5, verbose_name='Mayo'),
        ),
        migrations.AlterField(
            model_name='precio',
            name='noviembre',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=5, verbose_name='Noviembre'),
        ),
        migrations.AlterField(
            model_name='precio',
            name='octubre',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=5, verbose_name='Octubre'),
        ),
        migrations.AlterField(
            model_name='precio',
            name='septiembre',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=5, verbose_name='Septiembre'),
        ),
    ]
