# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-01 00:46
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amarreapp', '0047_auto_20170531_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='embarcacion',
            name='calado',
            field=models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(0.09), django.core.validators.MaxValueValidator(3.99)]),
        ),
        migrations.AlterField(
            model_name='embarcacion',
            name='motor_consumo',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='embarcacion',
            name='motor_num',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)]),
        ),
        migrations.AlterField(
            model_name='embarcacion',
            name='motor_potencia',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='embarcacion',
            name='motor_tipo',
            field=models.CharField(choices=[('I', 'Intraborda'), ('F', 'Fueraborda')], default='F', max_length=1),
        ),
        migrations.AlterField(
            model_name='embarcacion',
            name='velocidad_kn',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='prediccion',
            name='zona',
            field=models.CharField(choices=[('NO_MA', 'Noroeste Mallorca'), ('NE_MA', 'Noreste Mallorca'), ('ES_MA', 'Este Mallorca'), ('SU_MA', 'Sur Mallorca'), ('NO_ME', 'Norte Menorca'), ('SU_ME', 'Sur Menorca'), ('IBIZA', 'Ibiza')], default='NO_MA', max_length=5, verbose_name='zona'),
        ),
    ]
