# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-03 01:58
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('amarreapp', '0048_auto_20170601_0046'),
    ]

    operations = [
        migrations.CreateModel(
            name='DistanciaDestino',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distancia_nmi', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='distancia_nmi')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('ts', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='amarreapp.Puerto')),
            ],
        ),
    ]
