# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-04 02:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amarreapp', '0049_distanciadestino'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='distanciadestino',
            name='ts',
        ),
        migrations.DeleteModel(
            name='DistanciaDestino',
        ),
    ]
